###############################################################################
# Copyright (c) 2016 Dominique Lopes.
# All rights reserved. 
#
# This Source Code Form is subject to the terms of the Mozilla Public 
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Contributors:
#     Dominique Lopes - initial API and implementation
###############################################################################
config:
  url: http://www.finanzen.net/aktien/DAX-Realtimekurse
  defaultUser: user
  defaultPassword: password
  defaultRole: USER